image: golang:1.18

pipelines:
  default:
    - step:
        name: Lint code
        image: golangci/golangci-lint:v1.49.0
        script:
          - golangci-lint run -v
    - parallel:
      - step:
          name: Build Linux
          script:
            # Build compiles the packages
            - go build -o aware cmd/aware/main.go 
          artifacts:
            - aware
      - step:
          name: Build Windows
          script:
            # Build compiles the packages
            - env GOOS=windows GOARCH=amd64 go build -o aware.exe cmd/aware/main.go 
          artifacts:
            - aware.exe
